version: '2'
services:
  jhipstermysqlneo4jsample-app:
    image: jhipstermysqlneo4jsample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermysqlneo4jsample-mysql:3306/jhipstermysqlneo4jsample?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  jhipstermysqlneo4jsample-mysql:
    extends:
      file: mysql.yml
      service: jhipstermysqlneo4jsample-mysql
